enum Acoes {
  buscarLevantamentos,
  buscarLevantamento,
  buscarInventarios,
  buscarInventario,
  exluirLevantamentos,
  exluirLevantamento,
  enviaLevantamento,
  exluirInventarios,
  exluirInventario,
  enviaInventario,
  gerarArquivoBackup,
  lerBens,
  bensPrevistos,
  estatisticas,
}
